name: Laravel

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install composer
      run: docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php81-composer:latest \
        composer install --ignore-platform-reqs

    - name: Prepare
      run:
        composer require laravel/sail --dev
        php artisan sail:install
        ./vendor/bin/sail up -d

    - name: Run Tests
      run: ./vendor/bin/sail test
